if ("serviceWorker" in navigator) {
    navigator.serviceWorker
       .register("sw.js")
       .then(function(reg) {
          console.log("Service Worker Registered!", reg);

          reg.pushManager.getSubscription().then(function(sub) {
             if (sub === null) {
                // Update UI to ask user to register for Push
                console.log("Not subscribed to push service!");
             } else {
                // We have a subscription, update the database
                console.log("Subscription object: ", sub);
             }
          });
       })
       .catch(function(err) {
          console.log("Service Worker registration failed: ", err);
       });
 }

 // addEventListener('load', async ()=>{
 //     let sw = await navigator.serviceWorker.register('./sw.js')
 //     console.log(sw);
 // })

 async function subscribe() {
    //call push manager on sw
    let sw = await navigator.serviceWorker.ready;
    let push = await sw.pushManager.subscribe({
       userVisibleOnly: true,
       applicationServerKey:
          "BEupLAzaluKb5-uGeZbhN7H9UPMaRHk85IHD_qXZvTpBWvQZeo8Lo0Lk1cekr2iwNsl-Tdql2HyN8biVgswAJwU" //generated by web push package
       //public key on client, priv and pub on server
    });

    console.log(JSON.stringify(push)); //send back to server (api) and store in db
    // then when you want to send notifications, just iterate over these

    // let div = document.getElementById("endpoint");
    // div.innerHTML += JSON.stringify(push);
 }
